---
BREAKING:
 - '!:'
 - 'BREAKING'
build:
  - 'build: '
chore:
  - 'chore: '
docs:
  - 'docs: '
feat:
  - 'feat: '
fix:
  - 'fix: '
perf:
  - 'perf: '
refactor:
  - 'refactor: '
revert:
  - 'revert: '
style:
  - 'style: '
test:
  - 'test: '
temp:
  - 'temp: '
