---
name: Close the linked JIRA ticket
on:
  issues:
    types:
    - closed
jobs:
  close-jira-ticket:
    runs-on: ubuntu-latest
    steps:
    - uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - uses: atlassian/gajira-find-issue-key@master
      id: find
      with:
        string: ${{ github.event.issue.title }}
        from: ''
    - name: Close issue
      if: steps.find.outputs.issue
      id: close
      uses: atlassian/gajira-transition@master
      with:
        issue: "${{ steps.find.outputs.issue }}"
        transition: "Done"
