---
name: Transition JIRA ticket
on:
  issues:
    types:
    - labeled
jobs:
  transition-jira-ticket:
    if: secrets.JIRA_API_TOKEN
    runs-on: ubuntu-latest
    steps:
    - uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - uses: atlassian/gajira-find-issue-key@master
      id: find
      with:
        string: ${{ github.event.issue.title }}
        from: ''
    - name: Mark as TODO
      if: steps.find.outputs.issue && github.event.label.name == 'todo'
      uses: atlassian/gajira-transition@master
      with:
        issue: "${{ steps.find.outputs.issue }}"
        transition: "Todo"
    - name: Mark as in-progress
      if: steps.find.outputs.issue && github.event.label.name == 'progress'
      uses: atlassian/gajira-transition@master
      with:
        issue: "${{ steps.find.outputs.issue }}"
        transition: "In progress"
    - name: Mark as done
      if: steps.find.outputs.issue && github.event.label.name == 'done'
      uses: atlassian/gajira-transition@master
      with:
        issue: "${{ steps.find.outputs.issue }}"
        transition: "Done"
