---
name: Create JIRA ticket to track
on:
  issues:
    types:
    - opened
jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest
    steps:
    - uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - uses: atlassian/gajira-create@master
      id: create
      with:
        project: CENG
        issuetype: Task
        summary: |
          [PUBLIC] ${{ github.event.issue.title }}
        description: |
          ${{ github.event.issue.description }}
          ---
          This is an internal ticket to track a public one.
          Changes and comments made here are _not_ synced to Github.
          Public comments should be made directly to the Github Issue at
          ${{ github.event.issue.html_url }}
          ---
          ${{ toJSON(github.event.issue) }}
        # fields: '{"customfield_10171": "test"}'
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
    - run: |
        curl \
            -X PATCH \
            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            --data '{"title": "${{ github.event.issue.title }} [${{ steps.create.outputs.issue }}]"}' \
            "https://api.github.com/repos/${{ github.event.repository.full_name }}/issues/${{ github.event.issue.number }}" \
        ;
