---
name: 'Issue Labeler'
on:
  issues:
    types:
    - opened
    - edited
    - labeled
jobs:
  workflow-done:
    if: github.event.label.name == 'done'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Mark as done
      uses: andymckay/labeler@978f846c4ca6299fd136f465b42c5e87aca28cac
      with:
        remove-labels: 'progress,todo,triage'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Close the issue
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          Marked as done.
  workflow-progress:
    if: github.event.label.name == 'progress'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Mark as in-progress
      uses: andymckay/labeler@978f846c4ca6299fd136f465b42c5e87aca28cac
      with:
        remove-labels: 'done,todo,triage'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Add to Doing list
      uses: technote-space/create-project-card-action@v1
      with:
        PROJECT: backlog
        COLUMN: Doing
  workflow-todo:
    if: github.event.label.name == 'todo'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Mark as TODO
      uses: andymckay/labeler@978f846c4ca6299fd136f465b42c5e87aca28cac
      with:
        remove-labels: 'done,progress,triage'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Add to backlog
      uses: technote-space/create-project-card-action@v1
      with:
        PROJECT: backlog
        COLUMN: TODO
  workflow-triage:
    if: github.event.label.name == 'triage'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Mark as in-triage
      uses: andymckay/labeler@978f846c4ca6299fd136f465b42c5e87aca28cac
      with:
        remove-labels: 'done,progress,todo'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Add to backlog
      uses: technote-space/create-project-card-action@v1
      with:
        PROJECT: backlog
        COLUMN: TODO
