name: Handle Standup
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  standup:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: read
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
    - uses: actions/checkout@v2
    - run: pwd
    - run: ls
    - run: ls -la
    - run: pip install -r .github/requirements.txt
    - run: |
        export BASENAME="$(date '+%Y/%m/%d')"
        echo "::set-output name=BASENAME::${BASENAME}"
      id: BASENAME
    - run: mkdir -p ./docs/standup/${{ steps.BASENAME.outputs.BASENAME }} || true
    - run: python3 .github/standup.py > ./docs/standup/${{ steps.BASENAME.outputs.BASENAME }}.markdown
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: cat ./docs/standup/${{ steps.BASENAME.outputs.BASENAME }}.markdown
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ./docs/standup/${{ steps.BASENAME.outputs.BASENAME }}.markdown
        update_existing: true
