name: Handle Standup
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  standup:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: read
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
        curl \
            -H 'Accept: application/vnd.github.inertia-preview+json' \
            https://api.github.com/projects/columns/14068734/cards \
        ;
    - uses: actions/checkout@v2
    - run: pwd
    - run: ls
    - run: ls -la
    - run: pip install -r .github/requirements.txt
    - run: python3 .github/standup.py > ./standup.markdown
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: cat ./standup.markdown
