name: Handle Standup
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  standup:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: read
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
    - uses: octokit/request-action@v2.x
      id: get_column_cards
      with:
        route: GET /projects/columns/14068734/cards
        column_id: GET /projects/columns/{column_id}/cards
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: "echo latest release: ${{ steps.get_latest_release.outputs.data }}"
