name: Handle Standup
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  standup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      repository-projects: read
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
    - uses: actions/checkout@v2
    - run: pwd
    - run: ls
    - run: ls -la
    - run: pip install -r .github/requirements.txt
    - run: |
        export BASENAME="docs/standup/$(date '+%Y/%m')"
        export DATE="$(date '+%Y/%m/%d')"
        export FILENAME="$(date '+%d').markdown"
        export BRANCHNAME="$(date '+%Y/%m/%d').markdown"
        echo "BASENAME=${BASENAME}" >> "${GITHUB_ENV}"
        echo "FILENAME=${FILENAME}" >> "${GITHUB_ENV}"
        echo "BRANCHNAME=${BRANCHNAME}" >> "${GITHUB_ENV}"
        echo "DATE=${DATE}" >> "${GITHUB_ENV}"
        echo "::set-output name=BASENAME::${BASENAME}"
        echo "::set-output name=FILENAME::${FILENAME}"
        echo "::set-output name=BRANCHNAME::${BRANCHNAME}"
      id: BASENAME
    - run: mkdir -p ${{ steps.BASENAME.outputs.BASENAME }} || true
    - run: python3 .github/standup.py > ${{ steps.BASENAME.outputs.BASENAME }}/${{ steps.BASENAME.outputs.FILENAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: cat ${{ steps.BASENAME.outputs.BASENAME }}/${{ steps.BASENAME.outputs.FILENAME }}
    - uses: JasonEtco/create-an-issue@v2
      id: create
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ${{ steps.BASENAME.outputs.BASENAME }}/${{ steps.BASENAME.outputs.FILENAME}}
        update_existing: true
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        branch: standup/${{ env.DATE }}
        commit-message: |
            standup: ${{ env.DATE }}

            Closes: #${{ steps.create.outputs.number }}
        title: |
            standup: ${{ env.DATE }}
        body: |
            This is a PR body...
        labels: standup
        committer: "GitHub <noreply@github.com>"
        author: "GitHub <noreply@github.com>"
        # assignees: one, two
        # reviewers: one, two
        # team-reviewers: one, two
        # milestone: mklasdfas
