name: Handle Standup
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  standup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      repository-projects: read
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
    - uses: actions/checkout@v2
    - run: pip install -r .github/requirements.txt
    - run: |
        export DATE="$(date '+%Y-%m-%d')"
        export BRANCHNAME="standup/${DATE}"
        echo "BRANCHNAME=${BRANCHNAME}" >> "${GITHUB_ENV}"
        echo "DATE=${DATE}" >> "${GITHUB_ENV}"
    - run: |
        git config --global user.email 'noreply@github.com' \
        && git config --global user.name 'GitHub'
    - run: make standup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        branch: ${{ env.BRANCHNAME }}
        commit-message: |
            standup: ${{ env.DATE }}
        title: |
            standup: ${{ env.DATE }}
        body: |
            This is the day's standup.
        labels: standup
        committer: "GitHub <noreply@github.com>"
        author: "GitHub <noreply@github.com>"
