---
name: 'Sync status via labels'
on:
  issues:
    types:
    - opened
    - edited
    - labeled
jobs:
  workflow-done:
    if: github.event.label.name == 'done'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Mark as done
      uses: andymckay/labeler@978f846c4ca6299fd136f465b42c5e87aca28cac
      with:
        remove-labels: 'invalid,progress,todo,triage,wontfix'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Close the issue
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          Marked as done.
  workflow-invalid:
    if: github.event.label.name == 'invalid'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: andymckay/labeler@978f846c4ca6299fd136f465b42c5e87aca28cac
      with:
        remove-labels: 'done,progress,todo,triage,wontfix'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: peter-evans/close-issue@v1
  workflow-progress:
    if: github.event.label.name == 'progress'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write
    steps:
    - name: Mark as in-progress
      uses: andymckay/labeler@978f846c4ca6299fd136f465b42c5e87aca28cac
      with:
        remove-labels: 'done,invalid,todo,triage,wontfix'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: worklog
        column-name: Doing
  workflow-todo:
    if: github.event.label.name == 'todo'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Mark as TODO
      uses: andymckay/labeler@978f846c4ca6299fd136f465b42c5e87aca28cac
      with:
        remove-labels: 'done,invalid,progress,triage,wontfix'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: backlog
        column-name: TODO
    - uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: worklog
        column-name: TODO
  workflow-triage:
    if: github.event.label.name == 'triage'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Mark as in-triage
      uses: andymckay/labeler@978f846c4ca6299fd136f465b42c5e87aca28cac
      with:
        remove-labels: 'done,invalid,progress,todo,wontfix'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: backlog
        column-name: TODO
    - uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: worklog
        column-name: TODO
  workflow-wontfix:
    if: github.event.label.name == 'wontfix'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: andymckay/labeler@978f846c4ca6299fd136f465b42c5e87aca28cac
      with:
        remove-labels: 'done,invalid,progress,todo,triage'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: peter-evans/close-issue@v1
