---
name: 'Triage incoming issues'
on:
  issues:
    types:
    - opened
jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write
    steps:
    - name: initial labeling
      uses: andymckay/labeler@1.0.2
      with:
        add-labels: 'triage'
        ignore-if-assigned: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Add to backlog
      uses: technote-space/create-project-card-action@v1
      with:
        PROJECT: backlog
        COLUMN: TODO
    - uses: andymckay/labeler@1.0.2
      if: startsWith(github.event.issue.title, format('fix{0} ', '\:'))
      with:
        add-labels: 'bug'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
