---
name: 'Triage incoming issues'
on:
  issues:
    types:
    - opened
jobs:
  triage-incoming-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write
    steps:
    - uses: andymckay/labeler@1.0.2
      with:
        add-labels: 'triage'
        ignore-if-assigned: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: technote-space/create-project-card-action@v1
      with:
        PROJECT: backlog
        COLUMN: TODO
