---
name: 'Triage incoming issues'
on:
  issues:
    types:
    - opened
jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
    - name: initial labeling
      uses: andymckay/labeler@1.0.2
      with:
        add-labels: 'triage'
        ignore-if-labeled: true
